version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/kumparan
    depends_on:
      - database
    container_name: kumparan-go
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: kumparan
    container_name: kumparan-db
    ports:
      - 3306:3306
    volumes:
      - kumparan-data:/var/lib/mysql

# persisted storage
volumes:
  kumparan-data:
